[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/solmate/src/",
  "weird-erc20/=lib/weird-erc20/src/",
  "@chainlink/=lib/chainlink-brownie-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
